CREATE TABLE especialidade (
                               id int GENERATED BY DEFAULT AS IDENTITY,
                               nome varchar(100) NOT NULL,
                               CONSTRAINT pk_especialidade PRIMARY KEY (id)
);