CREATE TABLE endereco (
                          id int GENERATED BY DEFAULT AS IDENTITY,
                          rua varchar(150),
                          bairro varchar(100),
                          cidade varchar(100),
                          estado varchar(50),
                          CONSTRAINT pk_endereco PRIMARY KEY (id)
);