CREATE TABLE convenio (
                          id int GENERATED BY DEFAULT AS IDENTITY,
                          nome varchar(100) NOT NULL,
                          valor numeric(10,2),
                          CONSTRAINT pk_convenio PRIMARY KEY (id),
                          CONSTRAINT ck_convenio_valor CHECK (valor >= 0)
);

