CREATE TABLE medico (
                        id int GENERATED BY DEFAULT AS IDENTITY,
                        nome varchar(150) NOT NULL,
                        cpf varchar(11) NOT NULL,
                        endereco_id int UNIQUE,
                        CONSTRAINT pk_medico PRIMARY KEY (id),
                        CONSTRAINT uq_medico_cpf UNIQUE (cpf),
                        CONSTRAINT fk_medico_endereco FOREIGN KEY (endereco_id) REFERENCES endereco(id)
);
