CREATE TABLE paciente (
                          id int GENERATED BY DEFAULT AS IDENTITY,
                          nome varchar(150) NOT NULL,
                          cpf varchar(11) NOT NULL,
                          data_nascimento date,
                          telefone varchar(20),
                          email varchar(100),
                          convenio_id int,
                          endereco_id int UNIQUE,
                          CONSTRAINT pk_paciente PRIMARY KEY (id),
                          CONSTRAINT uq_paciente_cpf UNIQUE (cpf),
                          CONSTRAINT fk_paciente_convenio FOREIGN KEY (convenio_id) REFERENCES convenio(id),
                          CONSTRAINT fk_paciente_endereco FOREIGN KEY (endereco_id) REFERENCES endereco(id)
);
