CREATE TABLE consulta (
                          id int GENERATED BY DEFAULT AS IDENTITY,
                          valor numeric(10,2) CHECK (valor >= 0),
                          data_hora_inicio timestamp NOT NULL,
                          data_hora_fim timestamp,
                          realizado boolean DEFAULT FALSE,
                          medico_id int NOT NULL,
                          paciente_id int NOT NULL,
                          CONSTRAINT pk_consulta PRIMARY KEY (id),
                          CONSTRAINT fk_consulta_medico FOREIGN KEY (medico_id) REFERENCES medico(id),
                          CONSTRAINT fk_consulta_paciente FOREIGN KEY (paciente_id) REFERENCES paciente(id)
);
