CREATE TABLE pagamento_consulta (
                                    id int GENERATED BY DEFAULT AS IDENTITY,
                                    valor numeric(10,2) NOT NULL CHECK (valor >= 0),
                                    data_hora timestamp,
                                    realizado boolean DEFAULT FALSE,
                                    consulta_id int UNIQUE,
                                    CONSTRAINT pk_pagamento PRIMARY KEY (id),
                                    CONSTRAINT fk_pagamento_consulta FOREIGN KEY (consulta_id) REFERENCES consulta(id)
);
